// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group1CompStore.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Orders = new HashSet<Order>();
        }

        public int EmployeeId { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpSupervisor { get; set; }
        public string EmpEmail { get; set; }
        public string EmpJobTitle { get; set; }
        public string EmpStreet { get; set; }
        public string EmpCity { get; set; }
        public string EmpState { get; set; }
        public string EmpZip { get; set; }
        public DateTime? EmpDob { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}