// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group1CompStore.Models
{
    public partial class OrderPayment
    {
        public int OrderPaymentId { get; set; }
        public int CustomerId { get; set; }
        public int ReferenceNum { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Payment ReferenceNumNavigation { get; set; }
    }
}