// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group1CompStore.Models
{
    public partial class Payment
    {
        public Payment()
        {
            OrderPayments = new HashSet<OrderPayment>();
            Orders = new HashSet<Order>();
        }

        public int ReferenceNum { get; set; }
        public int CustomerId { get; set; }
        public DateTime PaymentDate { get; set; }
        public decimal PaidTotalPrice { get; set; }
        public decimal PaymentTax { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderPayment> OrderPayments { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}